env:
  # see https://github.com/SonarSource/re-terraform-aws-vault/blob/master/orders/bubble-cfamily.yaml
  CIRRUS_VAULT_URL: https://vault.sonar.build:8200
  CIRRUS_VAULT_AUTH_PATH: jwt-cirrusci
  CIRRUS_VAULT_ROLE: cirrusci-${CIRRUS_REPO_OWNER}-${CIRRUS_REPO_NAME}

  DOCKER_USERNAME: VAULT[development/kv/data/docker/sonardockerrw data.username]
  DOCKER_PASSWORD: VAULT[development/kv/data/docker/sonardockerrw data.access_token_rwd]

  # Mend scan global configuration  
  MEND_API_KEY: VAULT[development/kv/data/mend data.apikey]

  # Staging image configuration
  STAGING_IMAGE_NAME: sonarsource/sonarqube
  IMAGE_VERSION: 10.0.0
  SONAR_SCANNER_VERSION: 5.0.1

vm_instance_template: &VM_TEMPLATE
  experimental: true # see https://github.com/cirruslabs/cirrus-ci-docs/issues/1051
  image: docker-builder-v*
  type: t2.small
  region: eu-central-1
  subnet_id: ${CIRRUS_AWS_SUBNET}
  disk: 10
  cpu: 4
  memory: 16G

only_sonarsource_qa: &ONLY_SONARSOURCE_QA
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && $CIRRUS_TAG == "" && ($CIRRUS_PR != "" || $CIRRUS_BRANCH == $CIRRUS_DEFAULT_BRANCH || $CIRRUS_BRANCH =~ "branch-.*" || $CIRRUS_BUILD_SOURCE == 'api' )

build_task:
  <<: *ONLY_SONARSOURCE_QA
  env:
    FULL_VERSION: ${IMAGE_VERSION}.${CI_BUILD_NUMBER}_${SONAR_SCANNER_VERSION}
  ec2_instance:
    <<: *VM_TEMPLATE
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  build_script:
    - echo "Build and push the ${STAGING_IMAGE_NAME}:scanner-${FULL_VERSION} image"
    - > 
      docker build
      --annotation "org.opencontainers.image.title=SonarScanner CLI for SonarQube and SonarCloud"
      --annotation "org.opencontainers.image.description=SonarScanner is the official scanner used to run code analysis on SonarQube and SonarCloud"
      --annotation "org.opencontainers.image.vendor=SonarSource"
      --annotation "org.opencontainers.image.url=https://hub.docker.com/r/sonarsource/sonar-scanner-cli"
      --annotation "org.opencontainers.image.source=https://github.com/my-organization/my-project/${CIRRUS_REPO_FULL_NAME}"
      --annotation "org.opencontainers.image.documentation=https://docs.sonarqube.org/latest/analysis/scan/sonarscanner/"
      --annotation "org.opencontainers.image.revision=${GIT_COMMIT}"
      --annotation "org.opencontainers.image.version=${FULL_VERSION}"
      --tag "${STAGING_IMAGE_NAME}:scanner-${FULL_VERSION}"
      --push
      .

private_scan_task:
  # run only on master and long-term branches
  only_if: $CIRRUS_USER_COLLABORATOR == 'true' && ($CIRRUS_BRANCH == "master" || $CIRRUS_BRANCH =~ "branch-.*")
  env:
    FULL_VERSION: ${IMAGE_VERSION}.${CI_BUILD_NUMBER}_${SONAR_SCANNER_VERSION}
  ec2_instance:
    <<: *VM_TEMPLATE
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  setup_script:
    - apt-get remove -y unattended-upgrades
    - apt-get update && apt-get install -y --no-install-recommends openjdk-17-jre
    - curl -sSL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar -o wss-unified-agent.jar
    - echo "docker.includes=.*${STAGING_IMAGE_NAME}.*" >> .cirrus/wss-unified-agent.config
  scan_script:
    - echo "Scan the ${STAGING_IMAGE_NAME}:scanner-${FULL_VERSION} image"
    - docker pull "${STAGING_IMAGE_NAME}:scanner-${FULL_VERSION}"
    - java -jar wss-unified-agent.jar -c .cirrus/wss-unified-agent.config -apiKey $MEND_API_KEY
depends_on: build

public_scan_task: 
  only_if: $CIRRUS_CRON == 'nightly-mend-scan'
  env:
    PUBLIC_IMAGE_NAME: sonarsource/sonar-scanner-cli
    TAG: latest
  ec2_instance:
    <<: *VM_TEMPLATE
  setup_script:
    - apt-get remove -y unattended-upgrades
    - apt-get update && apt-get install -y --no-install-recommends openjdk-17-jre
    - curl -sSL https://unified-agent.s3.amazonaws.com/wss-unified-agent.jar -o wss-unified-agent.jar
    - echo "docker.includes=.*${TAG}.*" >> .cirrus/wss-unified-agent.config
  scan_script:
    - echo "Scan the ${PUBLIC_IMAGE_NAME}:${TAG} image"
    - docker pull "${PUBLIC_IMAGE_NAME}:${TAG}"
    - java -jar wss-unified-agent.jar -c .cirrus/wss-unified-agent.config -apiKey $MEND_API_KEY

test_docker_builder:
  env:
    FULL_VERSION: ${IMAGE_VERSION}.${CI_BUILD_NUMBER}_${SONAR_SCANNER_VERSION}
  login_script:
    - docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
  test_script:
    - apt-get update && apt-get install -qy bats
    - echo "Checking out the sonar-scanning-examples repository"
    - git clone https://github.com/SonarSource/sonar-scanning-examples.git target_repository
    - echo "Test the ${STAGING_IMAGE_NAME}:scanner-${FULL_VERSION} image"
    - TEST_IMAGE="${STAGING_IMAGE_NAME}:scanner-${FULL_VERSION}" bats --tap test
  depends_on: build

sonar_scan_task:
  eks_container:
    region: eu-central-1
    cluster_name: ${CIRRUS_CLUSTER_NAME}
    namespace: default
    image: sonarsource/sonar-scanner-cli:latest
    cpu: 4
    memory: 4G
  env:
    SONAR_TOKEN: VAULT[development/kv/data/next data.token]
    SONAR_HOST_URL: VAULT[development/kv/data/next data.url]
  script:
    - source .cirrus/scan.sh
  depends_on: build
